create or replace TABLE CONFIG_ALL.STAGE_FILE_TABLE_MAPPING_PW (
	CALC_DT DATE NOT NULL,
	STAGE_PATH VARCHAR(16777216) NOT NULL,
	FILE_NAMES VARCHAR(16777216) NOT NULL,
	BASE_NAME VARCHAR(16777216) NOT NULL,
	RAW_TABLE VARCHAR(16777216) NOT NULL,
	RAW_LOADED BOOLEAN,
	HIST_TABLE VARCHAR(16777216) NOT NULL,
	HIST_LOADED BOOLEAN,
	ENABLE_IND VARCHAR(1),
	LAST_LOAD_DTTM TIMESTAMP_NTZ(9),
	LAST_UPDATE_DTTM TIMESTAMP_NTZ(9),
	primary key (CALC_DT, STAGE_PATH, BASE_NAME)
);