create or replace TABLE CONFIG_LKP.LKP_ETL_STAGE_FLEETCO_ID (
	FLEETCO_ID_INPUT VARCHAR(50) NOT NULL,
	FLEETCO_ID NUMBER(38,0),
	START_DT DATE NOT NULL,
	END_DT DATE,
	FLEETCO_ENTITY VARCHAR(50),
	constraint PK primary key (FLEETCO_ID_INPUT, START_DT)
);