-- =====================================================
-- CLIENT_INPUTS_COMBINED ETL Configuration
-- =====================================================
-- This script creates a JSON configuration for the CLIENT_INPUTS_COMBINED table
-- that can be used with the LOAD_TABLE_DYNAMIC procedure
-- 
-- Author: AI Assistant
-- Date: 2025-01-27
-- Purpose: Generate ETL configuration for CLIENT_INPUTS_COMBINED table

-- =====================================================
-- CONFIGURATION JSON
-- =====================================================
-- This JSON configuration replicates the logic from POPULATE_CLIENT_INPUTS_COMBINED
-- but in a format compatible with LOAD_TABLE_DYNAMIC

WITH config_json AS (
    SELECT '{
  "columns": [
    {
      "data_type": "DATE",
      "ordinal_position": 1,
      "source": "A.CALC_DT",
      "target": "CALC_DT",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "VARCHAR(16777216)",
      "ordinal_position": 2,
      "source": "A.ASSETNUMBER",
      "target": "ASSET_ID",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "NUMBER(38,0)",
      "ordinal_position": 3,
      "source": "F.FLEETCO_ID",
      "target": "FLEETCO_ID",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "BOOLEAN",
      "ordinal_position": 4,
      "source": "FALSE",
      "target": "INELIGIBLE_IND",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "TIMESTAMP_NTZ(9)",
      "ordinal_position": 6,
      "source": "CURRENT_TIMESTAMP()",
      "target": "LOAD_TIMESTAMP",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "VARCHAR(16777216)",
      "ordinal_position": 7,
      "source": "''Inputs_Combined_V1''",
      "target": "MAPPING_ID",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "VARIANT",
      "ordinal_position": null,
      "source": "OBJECT_CONSTRUCT_KEEP_NULL(''A_ASSETNUMBER'', A.ASSETNUMBER, ''A_CLIENTNUMBER'', A.CLIENTNUMBER, ''A_ASSETSUFFIX'', A.ASSETSUFFIX, ''A_VIN'', A.VIN, ''A_LENDERCODE'', A.LENDERCODE, ''A_MAKE'', A.MAKE, ''A_BASEMODEL'', A.BASEMODEL, ''A_MODELYEAR'', A.MODELYEAR, ''A_VEHICLETRIM'', A.VEHICLETRIM, ''A_VEHICLETYPE'', A.VEHICLETYPE, ''A_VEHICLETYPEDETAIL'', A.VEHICLETYPEDETAIL, ''A_PROGRAMTYPE'', A.PROGRAMTYPE, ''A_GVWR'', A.GVWR, ''A_VEHICLEPAIDDATE'', A.VEHICLEPAIDDATE, ''A_VEHICLEDELIVERYDATE'', A.VEHICLEDELIVERYDATE, ''A_DELIVERYINPROCESSDAYCOUNT'', A.DELIVERYINPROCESSDAYCOUNT, ''A_DELIVERYINPROCESSINDICATOR'', A.DELIVERYINPROCESSINDICATOR, ''A_MSORECEIVEDDATE'', A.MSORECEIVEDDATE, ''A_MSOSENTDATE'', A.MSOSENTDATE, ''A_TITLEAPPLIEDDATE'', A.TITLEAPPLIEDDATE, ''A_TITLEFEEPAIDDATE'', A.TITLEFEEPAIDDATE, ''A_TITLERECEIVEDDATE'', A.TITLERECEIVEDDATE, ''A_TITLESTATE'', A.TITLESTATE, ''A_TAGSTATE'', A.TAGSTATE, ''A_SOLDDATE'', A.SOLDDATE, ''A_CASUALTYDATE'', A.CASUALTYDATE, ''A_CASUALTYIND'', A.CASUALTYIND, ''A_GROSSSALEAMOUNT'', A.GROSSSALEAMOUNT, ''A_SELLINGCOSTS'', A.SELLINGCOSTS, ''A_NETSALEAMOUNT'', A.NETSALEAMOUNT, ''A_DISPOSALDAYS'', A.DISPOSALDAYS, ''A_NETGAINLOSS'', A.NETGAINLOSS, ''A_SYNDICATIONSTATUS'', A.SYNDICATIONSTATUS, ''A_SYNDICATIONSTATUSDAYS'', A.SYNDICATIONSTATUSDAYS, ''A_VENDORINVOICEAMOUNT'', A.VENDORINVOICEAMOUNT, ''A_UPFITIND'', A.UPFITIND, ''A_UPFITTYPE'', A.UPFITTYPE, ''A_UPFITCOST'', A.UPFITCOST, ''A_UPFITCOSTPAID'', A.UPFITCOSTPAID, ''A_UPFITSTATUS'', A.UPFITSTATUS, ''A_UPFITDAYS'', A.UPFITDAYS, ''A_CURRENCYCODE'', A.CURRENCYCODE, ''A_VEHICLESTATUS'', A.VEHICLESTATUS, ''A_VEHICLESTATUSDESCRIPTION'', A.VEHICLESTATUSDESCRIPTION, ''A_INSERTDATE'', A.INSERTDATE, ''A_ASSETTYPE'', A.ASSETTYPE, ''A_LPORDEREDDATE'', A.LPORDEREDDATE, ''A_UPFITACTUALSTARTDATEKEY'', A.UPFITACTUALSTARTDATEKEY, ''A_UPFITACTUALCOMPLETEDATEKEY'', A.UPFITACTUALCOMPLETEDATEKEY, ''A_UPFITCOMPLETEDATEKEY'', A.UPFITCOMPLETEDATEKEY, ''A_UPFITVEHICLERECEIVEDDATEKEY'', A.UPFITVEHICLERECEIVEDDATEKEY, ''A_SHIPTOUPFITDATEKEY'', A.SHIPTOUPFITDATEKEY, ''A_SHIPPEDFROMUPFITDATEKEY'', A.SHIPPEDFROMUPFITDATEKEY, ''A_MARKETCLASS'', A.MARKETCLASS, ''A_SETTLEMENTTYPE'', A.SETTLEMENTTYPE, ''A_CLOSEDENDNETGAINLOSS'', A.CLOSEDENDNETGAINLOSS, ''A_CHROMESTYLEID'', A.CHROMESTYLEID, ''A_SCHEDULEDMIGRATIONDATE'', A.SCHEDULEDMIGRATIONDATE, ''A_DATEMIGRATED'', A.DATEMIGRATED, ''A_FUELTYPE'', A.FUELTYPE, ''C_CLIENTKEY'', C.CLIENTKEY, ''C_CLIENTID'', C.CLIENTID, ''C_PARENTCLIENTID'', C.PARENTCLIENTID, ''C_CLIENTNAME'', C.CLIENTNAME, ''C_CLIENTGROUP'', C.CLIENTGROUP, ''C_CLIENTTYPE'', C.CLIENTTYPE, ''C_ADDRESS1'', C.ADDRESS1, ''C_ADDRESS2'', C.ADDRESS2, ''C_ADDRESS3'', C.ADDRESS3, ''C_CITY'', C.CITY, ''C_COUNTY'', C.COUNTY, ''C_STATE'', C.STATE, ''C_ZIP'', C.ZIP, ''C_COUNTRY'', C.COUNTRY, ''C_PHONE'', C.PHONE, ''C_FAX'', C.FAX, ''C_MINLEASETERMS'', C.MINLEASETERMS, ''C_MAXLEASETERMS'', C.MAXLEASETERMS, ''C_CREDITSUSPENDED'', C.CREDITSUSPENDED, ''C_CONTACTNAME'', C.CONTACTNAME, ''C_ACTIVEVEHICLES'', C.ACTIVEVEHICLES, ''C_ACTIVE'', C.ACTIVE, ''C_INSERTDATE'', C.INSERTDATE, ''C_LASTUPDATE'', C.LASTUPDATE, ''C_BRAND'', C.BRAND, ''C_LEVELDISPLAY'', C.LEVELDISPLAY, ''C_LEVEL1HEADER'', C.LEVEL1HEADER, ''C_LEVEL2HEADER'', C.LEVEL2HEADER, ''C_LEVEL3HEADER'', C.LEVEL3HEADER, ''C_LEVEL4HEADER'', C.LEVEL4HEADER, ''C_LEVEL5HEADER'', C.LEVEL5HEADER, ''C_LEVEL6HEADER'', C.LEVEL6HEADER, ''C_LEVEL7HEADER'', C.LEVEL7HEADER, ''C_LEVEL8HEADER'', C.LEVEL8HEADER, ''C_LEVEL9HEADER'', C.LEVEL9HEADER, ''C_LEVEL10HEADER'', C.LEVEL10HEADER, ''C_MEDIA1HEADER'', C.MEDIA1HEADER, ''C_MEDIA2HEADER'', C.MEDIA2HEADER, ''C_UNASSIGNEDDRIVERNUMBER'', C.UNASSIGNEDDRIVERNUMBER, ''C_ALLIANCEINDICATOR'', C.ALLIANCEINDICATOR, ''C_FMTYPE'', C.FMTYPE, ''C_PUBLICCOMPANYFLAG'', C.PUBLICCOMPANYFLAG, ''C_SMALLFLEETFLAG'', C.SMALLFLEETFLAG, ''C_CREDITEXPIRATIONDATE'', C.CREDITEXPIRATIONDATE, ''C_SALESPERSON'', C.SALESPERSON, ''C_ACCOUNTMANAGER'', C.ACCOUNTMANAGER, ''C_FLEETPOTENTIAL'', C.FLEETPOTENTIAL, ''C_MARKET'', C.MARKET, ''C_MARKETDESCRIPTION'', C.MARKETDESCRIPTION, ''C_CHANNEL'', C.CHANNEL, ''C_CHANNELDESCRIPTION'', C.CHANNELDESCRIPTION, ''C_CLIENTFEDERALID'', C.CLIENTFEDERALID, ''C_BENEFITREPORTINGFLAG'', C.BENEFITREPORTINGFLAG, ''C_PMRYEARSTARTMONTH'', C.PMRYEARSTARTMONTH, ''C_VACATIONREPORTINGFLAG'', C.VACATIONREPORTINGFLAG, ''C_RENTALREPORTINGFLAG'', C.RENTALREPORTINGFLAG, ''C_SICCODE'', C.SICCODE, ''C_CLIENTSTATUS'', C.CLIENTSTATUS, ''C_ACCOUNTTYPE'', C.ACCOUNTTYPE, ''L_ASSETNUMBER'', L.ASSETNUMBER, ''L_CLIENTNUMBER'', L.CLIENTNUMBER, ''L_ASSETSUFFIX'', L.ASSETSUFFIX, ''L_VIN'', L.VIN, ''L_CONTRACTNUMBER'', L.CONTRACTNUMBER, ''L_LEASESTATUS'', L.LEASESTATUS, ''L_LEASEINELIGIBLEIND'', L.LEASEINELIGIBLEIND, ''L_LEASETYPE'', L.LEASETYPE, ''L_LEASETYPEDETAIL'', L.LEASETYPEDETAIL, ''L_UNAFFIRMEDLEASEIND'', L.UNAFFIRMEDLEASEIND, ''L_LEASECURRENCYCODE'', L.LEASECURRENCYCODE, ''L_FIXEDTERMLEASEIND'', L.FIXEDTERMLEASEIND, ''L_PAYMENTFREQUENCY'', L.PAYMENTFREQUENCY, ''L_ORIGINALLEASETERM'', L.ORIGINALLEASETERM, ''L_REMAININGMONTHS'', L.REMAININGMONTHS, ''L_MONTHSBILLED'', L.MONTHSBILLED, ''L_BASEINSTRUMENTRATENAME'', L.BASEINSTRUMENTRATENAME, ''L_BASEINSTRUMENTRATE'', L.BASEINSTRUMENTRATE, ''L_SPREADRATE'', L.SPREADRATE, ''L_LEASERATE'', L.LEASERATE, ''L_ADMINRATETYPE'', L.ADMINRATETYPE, ''L_ADMINRATE'', L.ADMINRATE, ''L_DEPRECIATIONRATE'', L.DEPRECIATIONRATE, ''L_DEPRECIATIONTERM'', L.DEPRECIATIONTERM, ''L_CAPCOSTOPEN'', L.CAPCOSTOPEN, ''L_CAPCOSTPAID'', L.CAPCOSTPAID, ''L_CAPCOSTTOTAL'', L.CAPCOSTTOTAL, ''L_ACCUMDEPRECIATION'', L.ACCUMDEPRECIATION, ''L_REMAININGBOOKVALUE'', L.REMAININGBOOKVALUE, ''L_REAMORTIZATIONIND'', L.REAMORTIZATIONIND, ''L_REAMORTIZATIONDATE'', L.REAMORTIZATIONDATE, ''L_REAMORTIZATIONTYPES'', L.REAMORTIZATIONTYPES, ''L_SELLFEE'', L.SELLFEE, ''L_PAIDSELLFEE'', L.PAIDSELLFEE, ''L_UNPAIDSELLFEE'', L.UNPAIDSELLFEE, ''L_RESIDUALVALUE'', L.RESIDUALVALUE, ''L_RESIDUALVALUEDATE'', L.RESIDUALVALUEDATE, ''L_REFERENCERESIDUALVALUE'', L.REFERENCERESIDUALVALUE, ''L_REFERENCERESIDUALNAME'', L.REFERENCERESIDUALNAME, ''L_REFERENCERESIDUALVALUEDATE'', L.REFERENCERESIDUALVALUEDATE, ''L_UNPAIDPRINCIPALRENT'', L.UNPAIDPRINCIPALRENT, ''L_TRACAMOUNT'', L.TRACAMOUNT, ''L_TRACPAIDAMOUNT'', L.TRACPAIDAMOUNT, ''L_TRACOPENAMOUNT'', L.TRACOPENAMOUNT, ''L_CHARGEOFFDATE'', L.CHARGEOFFDATE, ''L_CHARGEOFFAMOUNT'', L.CHARGEOFFAMOUNT, ''L_RECOVERYDATE'', L.RECOVERYDATE, ''L_RECOVERYAMOUNT'', L.RECOVERYAMOUNT, ''L_TERMINATIONDATE'', L.TERMINATIONDATE, ''L_INTERNALCAPCOST'', L.INTERNALCAPCOST, ''L_INTERNALNETBOOKVALUE'', L.INTERNALNETBOOKVALUE, ''L_DATEFUNDED'', L.DATEFUNDED, ''L_INSERTDATE'', L.INSERTDATE, ''L_DISPOSALFEETYPE'', L.DISPOSALFEETYPE, ''L_DISPOSALFEE'', L.DISPOSALFEE, ''L_INTERESTRATETYPE'', L.INTERESTRATETYPE, ''L_ENDOFTERMBILLINGTYPE'', L.ENDOFTERMBILLINGTYPE, ''L_ENDOFTERMAMOUNT'', L.ENDOFTERMAMOUNT, ''L_ENDOFTERMPERCENT'', L.ENDOFTERMPERCENT, ''L_ENDOFTERMBILLINGFLAG'', L.ENDOFTERMBILLINGFLAG, ''L_ANNUALADMINFEEAMOUNT'', L.ANNUALADMINFEEAMOUNT, ''L_ANNUALMINRENTAMOUNT'', L.ANNUALMINRENTAMOUNT)",
      "target": "ASSET_JSON",
      "target_type": "ASSET_JSON",
      "transformation": null
    },
    {
      "data_type": "VARIANT",
      "ordinal_position": null,
      "source": "COALESCE(RECV_AGG.RECV_JSON, ARRAY_CONSTRUCT())",
      "target": "RECV_JSON",
      "target_type": "RECV_JSON",
      "transformation": null
    }
  ],
  "filter_clause": "A.CALC_DT = DATE''{{ V_CALC_DT }}''",
  "group_by": null,
  "joins": [
    {
      "join_type": "LEFT",
      "table": "CLIENT_STAGE_T.LP_CLIENT_TEST_HIST",
      "alias": "C",
      "condition": "A.CALC_DT = C.CALC_DT AND A.CLIENTNUMBER = C.CLIENTID"
    },
    {
      "join_type": "LEFT",
      "table": "CLIENT_STAGE_T.LP_LEASE_TEST_HIST",
      "alias": "L",
      "condition": "L.CALC_DT = A.CALC_DT AND L.ASSETNUMBER = A.ASSETNUMBER AND L.CLIENTNUMBER = A.CLIENTNUMBER"
    },
    {
      "join_type": "INNER",
      "table": "CONFIG_LKP.LKP_ETL_STAGE_FLEETCO_ID",
      "alias": "F",
      "condition": "A.LENDERCODE = F.FLEETCO_ID_INPUT AND A.CALC_DT >= F.START_DT AND A.CALC_DT <= F.END_DT"
    },
    {
      "join_type": "LEFT",
      "table": "(SELECT A2.ASSETNUMBER AS ASSET_ID, ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(''INVOICENUMBER'', R.INVOICENUMBER, ''INVOICEDATE'', R.INVOICEDATE, ''INVOICEDUEDATE'', R.INVOICEDUEDATE, ''JDE_FLAG'', R.JDE_FLAG, ''CLIENTNUMBER'', R.CLIENTNUMBER, ''ASSETNUMBER'', R.ASSETNUMBER, ''ASSETSUFFIX'', R.ASSETSUFFIX, ''INVOICETOTAL'', R.INVOICETOTAL, ''ASSETINVOICETOTAL'', R.ASSETINVOICETOTAL, ''ASSETTRACTOTAL'', R.ASSETTRACTOTAL, ''ASSETPRINCIPALRENTTOTAL'', R.ASSETPRINCIPALRENTTOTAL, ''ASSETFLEETMANAGEMENTTOTAL'', R.ASSETFLEETMANAGEMENTTOTAL, ''ASSETSERVICERREIMBURSEMENTTOTAL'', R.ASSETSERVICERREIMBURSEMENTTOTAL, ''ASSETNONPRINCIPALRENTTOTAL'', R.ASSETNONPRINCIPALRENTTOTAL, ''ASSETINVOICEPERCENTAGE'', R.ASSETINVOICEPERCENTAGE, ''INVOICEGROSSAR'', R.INVOICEGROSSAR, ''INVOICEOPENAR'', R.INVOICEOPENAR, ''ASSETINVOICEGROSSAR'', R.ASSETINVOICEGROSSAR, ''ASSETINVOICEOPENAR'', R.ASSETINVOICEOPENAR, ''ASSETINVOICEOPENTRACAR'', R.ASSETINVOICEOPENTRACAR, ''ASSETINVOICEOPENPRINCIPALRENTAR'', R.ASSETINVOICEOPENPRINCIPALRENTAR, ''ASSETINVOICEOPENFLEETMANAGEMENTAR'', R.ASSETINVOICEOPENFLEETMANAGEMENTAR, ''ASSETINVOICEOPENSERVICERREIMBURSEMENTAR'', R.ASSETINVOICEOPENSERVICERREIMBURSEMENTAR, ''ASSETINVOICEOPENNONPRINCIPALRENTAR'', R.ASSETINVOICEOPENNONPRINCIPALRENTAR)) AS RECV_JSON FROM CLIENT_STAGE_T.LP_ASSET_TEST_HIST A2 LEFT JOIN CLIENT_STAGE_T.LP_ASSETINVOICEOPENAR_TEST_HIST R ON A2.CALC_DT = R.CALC_DT AND A2.ASSETNUMBER = R.ASSETNUMBER AND A2.CLIENTNUMBER = R.CLIENTNUMBER WHERE A2.CALC_DT = DATE''{{ V_CALC_DT }}'' GROUP BY A2.ASSETNUMBER)",
      "alias": "RECV_AGG",
      "condition": "A.ASSETNUMBER = RECV_AGG.ASSET_ID"
    }
  ],
  "source_alias": "A",
  "source_table": "CLIENT_STAGE_T.LP_ASSET_TEST_HIST",
  "target_table": "CLIENT_STAGE_T.CLIENT_INPUTS_COMBINED"
}' AS config_json
)
SELECT config_json FROM config_json;

-- =====================================================
-- INSERT CONFIGURATION INTO ETL_LOAD_CONFIG
-- =====================================================
-- Uncomment and run this section to insert the configuration

/*
INSERT INTO CONFIG_ALL.ETL_LOAD_CONFIG (
    PARENT,
    CONFIG_NAME,
    LOAD_TYPE,
    LOAD_LEVEL,
    LEVEL_VALUE,
    STEP,
    CONFIG_JSON,
    LAST_UPDATE_TIMESTAMP,
    LAST_UPDATE_BY
) VALUES (
    'CLIENT_STAGE_T',
    'POPULATE_CLIENT_INPUTS_COMBINED',
    'INSERT_DELETE',
    NULL,
    NULL,
    NULL,
    '{
  "columns": [
    {
      "data_type": "DATE",
      "ordinal_position": 1,
      "source": "A.CALC_DT",
      "target": "CALC_DT",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "VARCHAR(16777216)",
      "ordinal_position": 2,
      "source": "A.ASSETNUMBER",
      "target": "ASSET_ID",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "NUMBER(38,0)",
      "ordinal_position": 3,
      "source": "F.FLEETCO_ID",
      "target": "FLEETCO_ID",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "BOOLEAN",
      "ordinal_position": 4,
      "source": "FALSE",
      "target": "INELIGIBLE_IND",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "TIMESTAMP_NTZ(9)",
      "ordinal_position": 6,
      "source": "CURRENT_TIMESTAMP()",
      "target": "LOAD_TIMESTAMP",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "VARCHAR(16777216)",
      "ordinal_position": 7,
      "source": "''Inputs_Combined_V1''",
      "target": "MAPPING_ID",
      "target_type": "EXPOSED",
      "transformation": null
    },
    {
      "data_type": "VARIANT",
      "ordinal_position": null,
      "source": "OBJECT_CONSTRUCT_KEEP_NULL(''A_ASSETNUMBER'', A.ASSETNUMBER, ''A_CLIENTNUMBER'', A.CLIENTNUMBER, ''A_ASSETSUFFIX'', A.ASSETSUFFIX, ''A_VIN'', A.VIN, ''A_LENDERCODE'', A.LENDERCODE, ''A_MAKE'', A.MAKE, ''A_BASEMODEL'', A.BASEMODEL, ''A_MODELYEAR'', A.MODELYEAR, ''A_VEHICLETRIM'', A.VEHICLETRIM, ''A_VEHICLETYPE'', A.VEHICLETYPE, ''A_VEHICLETYPEDETAIL'', A.VEHICLETYPEDETAIL, ''A_PROGRAMTYPE'', A.PROGRAMTYPE, ''A_GVWR'', A.GVWR, ''A_VEHICLEPAIDDATE'', A.VEHICLEPAIDDATE, ''A_VEHICLEDELIVERYDATE'', A.VEHICLEDELIVERYDATE, ''A_DELIVERYINPROCESSDAYCOUNT'', A.DELIVERYINPROCESSDAYCOUNT, ''A_DELIVERYINPROCESSINDICATOR'', A.DELIVERYINPROCESSINDICATOR, ''A_MSORECEIVEDDATE'', A.MSORECEIVEDDATE, ''A_MSOSENTDATE'', A.MSOSENTDATE, ''A_TITLEAPPLIEDDATE'', A.TITLEAPPLIEDDATE, ''A_TITLEFEEPAIDDATE'', A.TITLEFEEPAIDDATE, ''A_TITLERECEIVEDDATE'', A.TITLERECEIVEDDATE, ''A_TITLESTATE'', A.TITLESTATE, ''A_TAGSTATE'', A.TAGSTATE, ''A_SOLDDATE'', A.SOLDDATE, ''A_CASUALTYDATE'', A.CASUALTYDATE, ''A_CASUALTYIND'', A.CASUALTYIND, ''A_GROSSSALEAMOUNT'', A.GROSSSALEAMOUNT, ''A_SELLINGCOSTS'', A.SELLINGCOSTS, ''A_NETSALEAMOUNT'', A.NETSALEAMOUNT, ''A_DISPOSALDAYS'', A.DISPOSALDAYS, ''A_NETGAINLOSS'', A.NETGAINLOSS, ''A_SYNDICATIONSTATUS'', A.SYNDICATIONSTATUS, ''A_SYNDICATIONSTATUSDAYS'', A.SYNDICATIONSTATUSDAYS, ''A_VENDORINVOICEAMOUNT'', A.VENDORINVOICEAMOUNT, ''A_UPFITIND'', A.UPFITIND, ''A_UPFITTYPE'', A.UPFITTYPE, ''A_UPFITCOST'', A.UPFITCOST, ''A_UPFITCOSTPAID'', A.UPFITCOSTPAID, ''A_UPFITSTATUS'', A.UPFITSTATUS, ''A_UPFITDAYS'', A.UPFITDAYS, ''A_CURRENCYCODE'', A.CURRENCYCODE, ''A_VEHICLESTATUS'', A.VEHICLESTATUS, ''A_VEHICLESTATUSDESCRIPTION'', A.VEHICLESTATUSDESCRIPTION, ''A_INSERTDATE'', A.INSERTDATE, ''A_ASSETTYPE'', A.ASSETTYPE, ''A_LPORDEREDDATE'', A.LPORDEREDDATE, ''A_UPFITACTUALSTARTDATEKEY'', A.UPFITACTUALSTARTDATEKEY, ''A_UPFITACTUALCOMPLETEDATEKEY'', A.UPFITACTUALCOMPLETEDATEKEY, ''A_UPFITCOMPLETEDATEKEY'', A.UPFITCOMPLETEDATEKEY, ''A_UPFITVEHICLERECEIVEDDATEKEY'', A.UPFITVEHICLERECEIVEDDATEKEY, ''A_SHIPTOUPFITDATEKEY'', A.SHIPTOUPFITDATEKEY, ''A_SHIPPEDFROMUPFITDATEKEY'', A.SHIPPEDFROMUPFITDATEKEY, ''A_MARKETCLASS'', A.MARKETCLASS, ''A_SETTLEMENTTYPE'', A.SETTLEMENTTYPE, ''A_CLOSEDENDNETGAINLOSS'', A.CLOSEDENDNETGAINLOSS, ''A_CHROMESTYLEID'', A.CHROMESTYLEID, ''A_SCHEDULEDMIGRATIONDATE'', A.SCHEDULEDMIGRATIONDATE, ''A_DATEMIGRATED'', A.DATEMIGRATED, ''A_FUELTYPE'', A.FUELTYPE, ''C_CLIENTKEY'', C.CLIENTKEY, ''C_CLIENTID'', C.CLIENTID, ''C_PARENTCLIENTID'', C.PARENTCLIENTID, ''C_CLIENTNAME'', C.CLIENTNAME, ''C_CLIENTGROUP'', C.CLIENTGROUP, ''C_CLIENTTYPE'', C.CLIENTTYPE, ''C_ADDRESS1'', C.ADDRESS1, ''C_ADDRESS2'', C.ADDRESS2, ''C_ADDRESS3'', C.ADDRESS3, ''C_CITY'', C.CITY, ''C_COUNTY'', C.COUNTY, ''C_STATE'', C.STATE, ''C_ZIP'', C.ZIP, ''C_COUNTRY'', C.COUNTRY, ''C_PHONE'', C.PHONE, ''C_FAX'', C.FAX, ''C_MINLEASETERMS'', C.MINLEASETERMS, ''C_MAXLEASETERMS'', C.MAXLEASETERMS, ''C_CREDITSUSPENDED'', C.CREDITSUSPENDED, ''C_CONTACTNAME'', C.CONTACTNAME, ''C_ACTIVEVEHICLES'', C.ACTIVEVEHICLES, ''C_ACTIVE'', C.ACTIVE, ''C_INSERTDATE'', C.INSERTDATE, ''C_LASTUPDATE'', C.LASTUPDATE, ''C_BRAND'', C.BRAND, ''C_LEVELDISPLAY'', C.LEVELDISPLAY, ''C_LEVEL1HEADER'', C.LEVEL1HEADER, ''C_LEVEL2HEADER'', C.LEVEL2HEADER, ''C_LEVEL3HEADER'', C.LEVEL3HEADER, ''C_LEVEL4HEADER'', C.LEVEL4HEADER, ''C_LEVEL5HEADER'', C.LEVEL5HEADER, ''C_LEVEL6HEADER'', C.LEVEL6HEADER, ''C_LEVEL7HEADER'', C.LEVEL7HEADER, ''C_LEVEL8HEADER'', C.LEVEL8HEADER, ''C_LEVEL9HEADER'', C.LEVEL9HEADER, ''C_LEVEL10HEADER'', C.LEVEL10HEADER, ''C_MEDIA1HEADER'', C.MEDIA1HEADER, ''C_MEDIA2HEADER'', C.MEDIA2HEADER, ''C_UNASSIGNEDDRIVERNUMBER'', C.UNASSIGNEDDRIVERNUMBER, ''C_ALLIANCEINDICATOR'', C.ALLIANCEINDICATOR, ''C_FMTYPE'', C.FMTYPE, ''C_PUBLICCOMPANYFLAG'', C.PUBLICCOMPANYFLAG, ''C_SMALLFLEETFLAG'', C.SMALLFLEETFLAG, ''C_CREDITEXPIRATIONDATE'', C.CREDITEXPIRATIONDATE, ''C_SALESPERSON'', C.SALESPERSON, ''C_ACCOUNTMANAGER'', C.ACCOUNTMANAGER, ''C_FLEETPOTENTIAL'', C.FLEETPOTENTIAL, ''C_MARKET'', C.MARKET, ''C_MARKETDESCRIPTION'', C.MARKETDESCRIPTION, ''C_CHANNEL'', C.CHANNEL, ''C_CHANNELDESCRIPTION'', C.CHANNELDESCRIPTION, ''C_CLIENTFEDERALID'', C.CLIENTFEDERALID, ''C_BENEFITREPORTINGFLAG'', C.BENEFITREPORTINGFLAG, ''C_PMRYEARSTARTMONTH'', C.PMRYEARSTARTMONTH, ''C_VACATIONREPORTINGFLAG'', C.VACATIONREPORTINGFLAG, ''C_RENTALREPORTINGFLAG'', C.RENTALREPORTINGFLAG, ''C_SICCODE'', C.SICCODE, ''C_CLIENTSTATUS'', C.CLIENTSTATUS, ''C_ACCOUNTTYPE'', C.ACCOUNTTYPE, ''L_ASSETNUMBER'', L.ASSETNUMBER, ''L_CLIENTNUMBER'', L.CLIENTNUMBER, ''L_ASSETSUFFIX'', L.ASSETSUFFIX, ''L_VIN'', L.VIN, ''L_CONTRACTNUMBER'', L.CONTRACTNUMBER, ''L_LEASESTATUS'', L.LEASESTATUS, ''L_LEASEINELIGIBLEIND'', L.LEASEINELIGIBLEIND, ''L_LEASETYPE'', L.LEASETYPE, ''L_LEASETYPEDETAIL'', L.LEASETYPEDETAIL, ''L_UNAFFIRMEDLEASEIND'', L.UNAFFIRMEDLEASEIND, ''L_LEASECURRENCYCODE'', L.LEASECURRENCYCODE, ''L_FIXEDTERMLEASEIND'', L.FIXEDTERMLEASEIND, ''L_PAYMENTFREQUENCY'', L.PAYMENTFREQUENCY, ''L_ORIGINALLEASETERM'', L.ORIGINALLEASETERM, ''L_REMAININGMONTHS'', L.REMAININGMONTHS, ''L_MONTHSBILLED'', L.MONTHSBILLED, ''L_BASEINSTRUMENTRATENAME'', L.BASEINSTRUMENTRATENAME, ''L_BASEINSTRUMENTRATE'', L.BASEINSTRUMENTRATE, ''L_SPREADRATE'', L.SPREADRATE, ''L_LEASERATE'', L.LEASERATE, ''L_ADMINRATETYPE'', L.ADMINRATETYPE, ''L_ADMINRATE'', L.ADMINRATE, ''L_DEPRECIATIONRATE'', L.DEPRECIATIONRATE, ''L_DEPRECIATIONTERM'', L.DEPRECIATIONTERM, ''L_CAPCOSTOPEN'', L.CAPCOSTOPEN, ''L_CAPCOSTPAID'', L.CAPCOSTPAID, ''L_CAPCOSTTOTAL'', L.CAPCOSTTOTAL, ''L_ACCUMDEPRECIATION'', L.ACCUMDEPRECIATION, ''L_REMAININGBOOKVALUE'', L.REMAININGBOOKVALUE, ''L_REAMORTIZATIONIND'', L.REAMORTIZATIONIND, ''L_REAMORTIZATIONDATE'', L.REAMORTIZATIONDATE, ''L_REAMORTIZATIONTYPES'', L.REAMORTIZATIONTYPES, ''L_SELLFEE'', L.SELLFEE, ''L_PAIDSELLFEE'', L.PAIDSELLFEE, ''L_UNPAIDSELLFEE'', L.UNPAIDSELLFEE, ''L_RESIDUALVALUE'', L.RESIDUALVALUE, ''L_RESIDUALVALUEDATE'', L.RESIDUALVALUEDATE, ''L_REFERENCERESIDUALVALUE'', L.REFERENCERESIDUALVALUE, ''L_REFERENCERESIDUALNAME'', L.REFERENCERESIDUALNAME, ''L_REFERENCERESIDUALVALUEDATE'', L.REFERENCERESIDUALVALUEDATE, ''L_UNPAIDPRINCIPALRENT'', L.UNPAIDPRINCIPALRENT, ''L_TRACAMOUNT'', L.TRACAMOUNT, ''L_TRACPAIDAMOUNT'', L.TRACPAIDAMOUNT, ''L_TRACOPENAMOUNT'', L.TRACOPENAMOUNT, ''L_CHARGEOFFDATE'', L.CHARGEOFFDATE, ''L_CHARGEOFFAMOUNT'', L.CHARGEOFFAMOUNT, ''L_RECOVERYDATE'', L.RECOVERYDATE, ''L_RECOVERYAMOUNT'', L.RECOVERYAMOUNT, ''L_TERMINATIONDATE'', L.TERMINATIONDATE, ''L_INTERNALCAPCOST'', L.INTERNALCAPCOST, ''L_INTERNALNETBOOKVALUE'', L.INTERNALNETBOOKVALUE, ''L_DATEFUNDED'', L.DATEFUNDED, ''L_INSERTDATE'', L.INSERTDATE, ''L_DISPOSALFEETYPE'', L.DISPOSALFEETYPE, ''L_DISPOSALFEE'', L.DISPOSALFEE, ''L_INTERESTRATETYPE'', L.INTERESTRATETYPE, ''L_ENDOFTERMBILLINGTYPE'', L.ENDOFTERMBILLINGTYPE, ''L_ENDOFTERMAMOUNT'', L.ENDOFTERMAMOUNT, ''L_ENDOFTERMPERCENT'', L.ENDOFTERMPERCENT, ''L_ENDOFTERMBILLINGFLAG'', L.ENDOFTERMBILLINGFLAG, ''L_ANNUALADMINFEEAMOUNT'', L.ANNUALADMINFEEAMOUNT, ''L_ANNUALMINRENTAMOUNT'', L.ANNUALMINRENTAMOUNT)",
      "target": "ASSET_JSON",
      "target_type": "ASSET_JSON",
      "transformation": null
    },
    {
      "data_type": "VARIANT",
      "ordinal_position": null,
      "source": "COALESCE(RECV_AGG.RECV_JSON, ARRAY_CONSTRUCT())",
      "target": "RECV_JSON",
      "target_type": "RECV_JSON",
      "transformation": null
    }
  ],
  "filter_clause": "A.CALC_DT = DATE''{{ V_CALC_DT }}''",
  "group_by": null,
  "joins": [
    {
      "join_type": "LEFT",
      "table": "CLIENT_STAGE_T.LP_CLIENT_TEST_HIST",
      "alias": "C",
      "condition": "A.CALC_DT = C.CALC_DT AND A.CLIENTNUMBER = C.CLIENTID"
    },
    {
      "join_type": "LEFT",
      "table": "CLIENT_STAGE_T.LP_LEASE_TEST_HIST",
      "alias": "L",
      "condition": "L.CALC_DT = A.CALC_DT AND L.ASSETNUMBER = A.ASSETNUMBER AND L.CLIENTNUMBER = A.CLIENTNUMBER"
    },
    {
      "join_type": "INNER",
      "table": "CONFIG_LKP.LKP_ETL_STAGE_FLEETCO_ID",
      "alias": "F",
      "condition": "A.LENDERCODE = F.FLEETCO_ID_INPUT AND A.CALC_DT >= F.START_DT AND A.CALC_DT <= F.END_DT"
    },
    {
      "join_type": "LEFT",
      "table": "(SELECT A2.ASSETNUMBER AS ASSET_ID, ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(''INVOICENUMBER'', R.INVOICENUMBER, ''INVOICEDATE'', R.INVOICEDATE, ''INVOICEDUEDATE'', R.INVOICEDUEDATE, ''JDE_FLAG'', R.JDE_FLAG, ''CLIENTNUMBER'', R.CLIENTNUMBER, ''ASSETNUMBER'', R.ASSETNUMBER, ''ASSETSUFFIX'', R.ASSETSUFFIX, ''INVOICETOTAL'', R.INVOICETOTAL, ''ASSETINVOICETOTAL'', R.ASSETINVOICETOTAL, ''ASSETTRACTOTAL'', R.ASSETTRACTOTAL, ''ASSETPRINCIPALRENTTOTAL'', R.ASSETPRINCIPALRENTTOTAL, ''ASSETFLEETMANAGEMENTTOTAL'', R.ASSETFLEETMANAGEMENTTOTAL, ''ASSETSERVICERREIMBURSEMENTTOTAL'', R.ASSETSERVICERREIMBURSEMENTTOTAL, ''ASSETNONPRINCIPALRENTTOTAL'', R.ASSETNONPRINCIPALRENTTOTAL, ''ASSETINVOICEPERCENTAGE'', R.ASSETINVOICEPERCENTAGE, ''INVOICEGROSSAR'', R.INVOICEGROSSAR, ''INVOICEOPENAR'', R.INVOICEOPENAR, ''ASSETINVOICEGROSSAR'', R.ASSETINVOICEGROSSAR, ''ASSETINVOICEOPENAR'', R.ASSETINVOICEOPENAR, ''ASSETINVOICEOPENTRACAR'', R.ASSETINVOICEOPENTRACAR, ''ASSETINVOICEOPENPRINCIPALRENTAR'', R.ASSETINVOICEOPENPRINCIPALRENTAR, ''ASSETINVOICEOPENFLEETMANAGEMENTAR'', R.ASSETINVOICEOPENFLEETMANAGEMENTAR, ''ASSETINVOICEOPENSERVICERREIMBURSEMENTAR'', R.ASSETINVOICEOPENSERVICERREIMBURSEMENTAR, ''ASSETINVOICEOPENNONPRINCIPALRENTAR'', R.ASSETINVOICEOPENNONPRINCIPALRENTAR)) AS RECV_JSON FROM CLIENT_STAGE_T.LP_ASSET_TEST_HIST A2 LEFT JOIN CLIENT_STAGE_T.LP_ASSETINVOICEOPENAR_TEST_HIST R ON A2.CALC_DT = R.CALC_DT AND A2.ASSETNUMBER = R.ASSETNUMBER AND A2.CLIENTNUMBER = R.CLIENTNUMBER WHERE A2.CALC_DT = DATE''{{ V_CALC_DT }}'' GROUP BY A2.ASSETNUMBER)",
      "alias": "RECV_AGG",
      "condition": "A.ASSETNUMBER = RECV_AGG.ASSET_ID"
    }
  ],
  "source_alias": "A",
  "source_table": "CLIENT_STAGE_T.LP_ASSET_TEST_HIST",
  "target_table": "CLIENT_STAGE_T.CLIENT_INPUTS_COMBINED"
}',
    CURRENT_TIMESTAMP(),
    'AI_ASSISTANT'
);
*/

-- =====================================================
-- USAGE EXAMPLE
-- =====================================================
/*
-- After inserting the configuration, you can use it with LOAD_TABLE_DYNAMIC:

-- 1. Create the table (optional - if it doesn''t exist)
CALL CLIENT_STAGE_T.LOAD_TABLE_DYNAMIC(
    'POPULATE_CLIENT_INPUTS_COMBINED',
    DATE'2025-04-30',
    TRUE  -- Create table
);

-- 2. Load data
CALL CLIENT_STAGE_T.LOAD_TABLE_DYNAMIC(
    'POPULATE_CLIENT_INPUTS_COMBINED',
    DATE'2025-04-30',
    FALSE  -- Don''t create table
);

-- 3. Verify results
SELECT 
    CALC_DT,
    ASSET_ID,
    FLEETCO_ID,
    INELIGIBLE_IND,
    ARRAY_SIZE(RECV_JSON) AS receivables_count,
    LOAD_TIMESTAMP,
    MAPPING_ID
FROM CLIENT_STAGE_T.CLIENT_INPUTS_COMBINED 
WHERE CALC_DT = DATE'2025-04-30'
ORDER BY ASSET_ID;
*/ 