CREATE OR REPLACE TABLE CLIENT_STAGE_T.ALTER_STATEMENTS_LOG (
    LOG_ID NUMBER AUTOINCREMENT,
    EXECUTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SCHEMA STRING,
    SOURCE_TABLE STRING,
    TARGET_SCHEMA STRING,
    TARGET_TABLE STRING,
    ACTION_TYPE STRING, -- 'LOG_ONLY' or 'EXECUTE'
    COLUMN_NAME STRING,
    ACTION STRING, -- 'ADD_COLUMN', 'ERROR', 'INFO'
    SQL_STATEMENT STRING,
    ERROR_MESSAGE STRING,
    STATUS STRING -- 'SUCCESS', 'ERROR', 'WARNING'
);