create or replace TABLE CLIENT_STAGE_T.CLIENT_INPUTS_COMBINED (
	CALC_DT DATE,
	ASSET_ID VARCHAR(16777216),
	FLEETCO_ID NUMBER(38,0),
	INELIGIBLE_IND BOOLEAN,
	ASSET_JSON VARIANT,
	RECV_JSON VARIANT,
	LOAD_TIMESTAMP TIMESTAMP_NTZ(9),
	MAPPING_ID VARCHAR(16777216)
);